version: "3"
services:
  couchbase-db:
    image: couchbase/server-sandbox:7.0.0
    deploy:
      replicas: 1
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11207:11207
      - 11210:11210